{% set name = "atom" %}
{% set version = "0.5.0" %}
{% set sha256 = "3f4dd1108be206d28eda23637a473561dea69a3d21d2896ed0594b88b302a482" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cppy
  run:
    - python
    - future

test:
  imports:
    - atom
    - atom.catom
    - atom.datastructures
    - atom.datastructures.sortedmap

about:
  home: https://github.com/nucleic/atom
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Memory efficient Python objects
  description: |
    Atom is a framework for creating memory efficient Python objects
    with enhanced features such as dynamic initialization, validation, and
    change notification for object attributes.
  doc_url: http://flight-manual.atom.io/
  dev_url: https://github.com/nucleic/atom

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
