{% set name = "atom" %}
{% set version = "0.8.2" %}
{% set sha256 = "3155b7a0a286cb5c2bff2929fc2341d071dc9169b0d0ff1f15450ddd57d24c57" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
    - cppy
  run:
    - python

test:
  imports:
    - atom
    - atom.catom
    - atom.datastructures
    - atom.datastructures.sortedmap
  commands:
    - pip check

about:
  home: https://github.com/nucleic/atom
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Memory efficient Python objects
  description: |
    Atom is a framework for creating memory efficient Python objects
    with enhanced features such as dynamic initialization, validation, and
    change notification for object attributes.
  doc_url: https://flight-manual.atom.io/
  dev_url: https://github.com/nucleic/atom

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
  skip-lints:
    - missing_license_url
    - missing_doc_source_url