{% set name = "atom" %}
{% set version = "0.9.0" %}
{% set sha256 = "eccc1ab0cc1c6d1ed5b6ecd1e768f8b8727447605bd009a2a0b49b4ee7eb963d" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - setuptools_scm
    - toml
    - cppy 1.2.1
  run:
    - python
    - typing_extensions  # [py<311]

test:
  requires:
    - pip
    - python
  imports:
    - atom
    - atom.catom
    - atom.datastructures
    - atom.datastructures.sortedmap
  commands:
    - pip check

about:
  home: https://github.com/nucleic/atom
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Memory efficient Python objects
  description: |
    Atom is a framework for creating memory efficient Python objects
    with enhanced features such as dynamic initialization, validation, and
    change notification for object attributes.
  doc_url: https://atom.readthedocs.io/
  dev_url: https://github.com/nucleic/atom

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
