{% set version = "0.4.0" %}
package:
  name: atom
  version: {{ version }}

source:
  url: https://github.com/nucleic/atom/archive/{{ version }}.tar.gz
  fn: atom-{{ version }}.tar.gz
  sha256: 0ad1c86c9d3cbca8489b386287ba2274591bff818a2944ffae8ed1af420e29ee

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python
    - future

test:
  imports:
    - atom
    - atom.catom
    - atom.datastructures
    - atom.datastructures.sortedmap

about:
  home: https://github.com/nucleic/atom
  license: BSD 3-Clause
  license: BSD
  license_file: COPYING.txt
  summary: Memory efficient Python objects
  description: |
    Atom is a framework for creating memory efficient Python objects
    with enhanced features such as dynamic initialization, validation, and
    change notification for object attributes.
  doc_url: http://flight-manual.atom.io/
  dev_url: https://github.com/nucleic/atom

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
