{% set name = "atom" %}
{% set version = "0.11.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ab93fc3cc7b6a078253b116e9f6235d2913eb9bb49adbc31a258e1017f2aee0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<310]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - wheel
    - setuptools >=61.2
    - cppy >=1.2.0
    # setuptools_scm[toml]>=3.4.3
    - setuptools_scm >=3.4.3
    - toml
  run:
    - python
    - typing_extensions  # [py<311]

test:
  source_files:
    - tests
  imports:
    - atom
    - atom.catom
    - atom.datastructures
    - atom.datastructures.sortedmap
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - python
    - pytest

about:
  home: https://github.com/nucleic/atom
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Memory efficient Python objects
  description: |
    Atom is a framework for creating memory efficient Python objects
    with enhanced features such as dynamic initialization, validation, and
    change notification for object attributes.
  doc_url: https://atom.readthedocs.io/
  dev_url: https://github.com/nucleic/atom

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
