{% set version = "0.4.1" %}
package:
  name: atom
  version: {{ version }}

source:
  url: https://github.com/nucleic/atom/archive/{{ version }}.tar.gz
  fn: atom-{{ version }}.tar.gz
  sha256: 86e3e25775c7a91d47689b310a1483cf140fa5a1401033aa1ea7f6a29efcd2a7

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python
    - future

test:
  imports:
    - atom
    - atom.catom
    - atom.datastructures
    - atom.datastructures.sortedmap

about:
  home: https://github.com/nucleic/atom
  license: BSD 3-Clause
  license: BSD
  license_file: COPYING.txt
  summary: Memory efficient Python objects
  description: |
    Atom is a framework for creating memory efficient Python objects
    with enhanced features such as dynamic initialization, validation, and
    change notification for object attributes.
  doc_url: http://flight-manual.atom.io/
  dev_url: https://github.com/nucleic/atom

extra:
  recipe-maintainers:
    - blink1073
    - ericdill
    - licode
    - MatthieuDartiailh
    - sccolbert
    - tacaswell
