travis:
  secure:
    BINSTAR_TOKEN: vx5/Gf9/Rt9gokWcpsgsFs+7obqlcJ6KC53iZFs4V1zEz5iaA++etd3jGydhMJfh6+uCMppA1ynEwovLM1YmlRISNpuo67oE8l9fMTsC6+OuzzgmVZ6WAk0oVCniXNR4GdqgHyrGvi5xVhsyj7y83WpJZclwfxYZ6b4cp46k3B7TUep3vBRemDPZK8kPt7/565bTqRNfDCnb6ZuIiuCf4hZWTJjzfVq8KpNjZEBieaSg1kmSk5J10ITwcJ6TX7leeums4M5bzNsuhrtjEh5FKgqfyxKRhC661Cdiqt26ZUktW8vBRdcAUE20XkSS+g6SdWYnWmnIwtCH3nfDewNOmktpo1tSAFP/XEiLB7BLnxNASOto1YFuQWRDCASivOhl90TZ7elmFAMIY/Tm1gLuUt00LKES0ykNX+G7o4pSPmA6dAeEhjAUsnw3VLWZ92/h6zNSWlpf5CeygqaAbRFh3aBWiH3AsApJTlPBtVUmMgIJ3/H2T69Yc0t9zqf7i/pEFHQZiTgmJ5R+PRR7ZOmulrB1oYNIP7VtOLJGNwLKgIkRqRfI0iknMHW+9dexjQYHHaC0xjlzVMd2jhEo3QmYpydzDSgiRoILvZONuENmgne69WQ9hY2wIDe3iIBVGUpKXxPbK8UoimhF07+4GaqnT/XABDbrO/YrqZr/wLNA/Gs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
